---
title: "Lab Exercise"
jupyter:
  jupytext:
    formats: ipynb,Rmd
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.11.2
  kernelspec:
    display_name: R
    language: R
    name: ir
---


# Lab: Introduction to R


## Basic Commands


```{r chunk1}
x <- c(1, 3, 2, 5)
x
```


```{r chunk2}
x = c(1, 6, 2)
x
y = c(1, 4, 3)
```


```{r chunk3}
length(x)
length(y)
x + y
```


```{r chunk4}
ls()
rm(x, y)
ls()
```



```{r chunk5}
rm(list = ls())
```



```{r chunk6}
?matrix
```


```{r chunk7}
x <- matrix(data = c(1, 2, 3, 4), nrow = 2, ncol = 2)
x
```


```{r chunk8}
x <- matrix(c(1, 2, 3, 4), 2, 2)
```



```{r chunk9}
matrix(c(1, 2, 3, 4), 2, 2, byrow = TRUE)
```



```{r chunk10}
sqrt(x)
x^2
```



```{r chunk11}
x <- rnorm(50)
y <- x + rnorm(50, mean = 50, sd = .1)
cor(x, y)
```


```{r chunk12}
set.seed(1303)
rnorm(50)
```


```{r chunk13}
set.seed(3)
y <- rnorm(100)
mean(y)
var(y)
sqrt(var(y))
sd(y)
```


## Graphics


```{r chunk14}
x <- rnorm(100)
y <- rnorm(100)
plot(x, y)
plot(x, y, xlab = "this is the x-axis",
    ylab = "this is the y-axis",
    main = "Plot of X vs Y")
```



```{r chunk15}
pdf("Figure.pdf")
plot(x, y, col = "green")
dev.off()
```



```{r chunk16}
x <- seq(1, 10)
x
x <- 1:10
x
x <- seq(-pi, pi, length = 50)
```



```{r chunk17}
y <- x
f <- outer(x, y, function(x, y) cos(y) / (1 + x^2))
contour(x, y, f)
contour(x, y, f, nlevels = 45, add = T)
fa <- (f - t(f)) / 2
contour(x, y, fa, nlevels = 15)
```



```{r chunk18}
image(x, y, fa)
persp(x, y, fa)
persp(x, y, fa, theta = 30)
persp(x, y, fa, theta = 30, phi = 20)
persp(x, y, fa, theta = 30, phi = 70)
persp(x, y, fa, theta = 30, phi = 40)
```


## Indexing Data

```{r chunk19}
A <- matrix(1:16, 4, 4)
A
```


```{r chunk20}
A[2, 3]
```


```{r chunk21}
A[c(1, 3), c(2, 4)]
A[1:3, 2:4]
A[1:2, ]
A[, 1:2]
```


```{r chunk22}
A[1, ]
```


```{r chunk23}
A[-c(1, 3), ]
A[-c(1, 3), -c(1, 3, 4)]
```


```{r chunk24}
dim(A)
```


## Loading Data


```{r chunk25}
Auto <- read.table("Auto.data")
View(Auto)
head(Auto)
```


```{r chunk26}
Auto <- read.table("Auto.data", header = T, na.strings = "?", stringsAsFactors = T)
View(Auto)
```


```{r chunk27}
Auto <- read.csv("Auto.csv", na.strings = "?", stringsAsFactors = T)
View(Auto)
dim(Auto)
Auto[1:4, ]
```


```{r chunk28}
Auto <- na.omit(Auto)
dim(Auto)
```


```{r chunk29}
names(Auto)
```


## Additional Graphical and Numerical Summaries


```{r chunk31}
plot(Auto$cylinders, Auto$mpg)
attach(Auto)
plot(cylinders, mpg)
```


```{r chunk32}
cylinders <- as.factor(cylinders)
```


```{r chunk33}
plot(cylinders, mpg)
plot(cylinders, mpg, col = "red")
plot(cylinders, mpg, col = "red", varwidth = T)
plot(cylinders, mpg, col = "red", varwidth = T,
    horizontal = T)
plot(cylinders, mpg, col = "red", varwidth = T,
    xlab = "cylinders", ylab = "MPG")
```


```{r chunk34}
hist(mpg)
hist(mpg, col = 2)
hist(mpg, col = 2, breaks = 15)
```


```{r chunk35}
pairs(Auto)
pairs(
    ~ mpg + displacement + horsepower + weight + acceleration,
    data = Auto
  )
```



```{r chunk36}
plot(horsepower, mpg)
identify(horsepower, mpg, name)
```



```{r chunk37}
summary(Auto)
```


```{r chunk38}
summary(mpg)
```
